config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
   get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :tweets
  post 'tweets/confirm', to: 'tweets#confirm', as: 'confirm'
  delete '/tweets/:id', to: 'tweets#destroy', as: 'destroy'
  root 'tweets#index'
  get '/exemple', to: 'tweets#base'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  before_action :authenticate_user!, only: [ :new, :create, :edit, :update, :destroy]

  # GET /tweets or /tweets.json
  def base
    render ""
  end


  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1 or /tweets/1.json
  def show
    @user = @tweet.user
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  def confirm
    @tweet = Tweet.new(tweet_params)
  end
  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json

  def delete_post
    connection.execute("DELETE FROM tweets WHERE tweets.id = ?", params['id'])

    redirect_to '/'
  end


  def destroy
    @tweet = Tweet.find(params[:id])

    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    def tweet_params
      params.require(:tweet).permit(:Title, :Content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tweets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    

<link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
  rel="stylesheet"
/>
<!-- Google Fonts -->
<link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  rel="stylesheet"
/>
<!-- MDB -->
<link
  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
  rel="stylesheet"
/>
  </head>

  <body>
    <header>
      <!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- Container wrapper -->
  <div class="container">
    <!-- Navbar brand -->
    <a class="navbar-brand">TWEET</a>

    <!-- Toggle button -->
    <button
      class="navbar-toggler"
      type="button"
      data-mdb-toggle="collapse"
      data-mdb-target="#navbarButtonsExample"
      aria-controls="navbarButtonsExample"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarButtonsExample">
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

      </ul>
      <!-- Left links -->

      <div class="d-flex align-items-center">
        <% if user_signed_in? %>
        <div class="container " style="text-align: right;">
          <strong style="color: blue; text-decoration: underline;">
            <%= link_to('Logout', destroy_user_session_path, method: :delete) %></strong>
        </div>

      <% else %>
        <div class="container " style="text-align: right;">
          <strong style="color: blue; text-decoration: underline;"><%= link_to('Login', new_user_session_path) %></strong>
          &nbsp;&nbsp;
          <strong style="color: blue; text-decoration: underline;"><a href="/users/sign_up">Sign Up</a></strong>
        </div>

      <% end %>


      </div>
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->
    </header>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

    <footer class="bg-light text-center text-lg-start ">
      <!-- Copyright -->
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2020 Copyright:
        <a class="text-dark" href="/">Tweet</a>
      </div>
      <!-- Copyright -->
    </footer>

    <!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
></script>
  </body>
</html>

app/views/layouts/base.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
      rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet"
    />
    <!-- MDB -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
      rel="stylesheet"
    />
    <title></title>
  </head>
  <body>


    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <!-- Container wrapper -->
      <div class="container">
        <!-- Navbar brand -->
        <a class="navbar-brand me-2" href="https://mdbgo.com/">
          <img
            src="https://mdbootstrap.com/img/logo/mdb-transaprent-noshadows.png"
            height="16"
            alt=""
            loading="lazy"
            style="margin-top: -1px;"
          />
        </a>

        <!-- Toggle button -->
        <button
          class="navbar-toggler"
          type="button"
          data-mdb-toggle="collapse"
          data-mdb-target="#navbarButtonsExample"
          aria-controls="navbarButtonsExample"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <i class="fas fa-bars"></i>
        </button>

        <!-- Collapsible wrapper -->
        <div class="collapse navbar-collapse" id="navbarButtonsExample">
          <!-- Left links -->
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="#">Dashboard</a>
            </li>
          </ul>
          <!-- Left links -->

          <div class="d-flex align-items-center">
            <button type="button" class="btn btn-link px-3 me-2">
              Login
            </button>
            <button type="button" class="btn btn-primary me-3">
              Sign up for free
            </button>
            <a
              class="btn btn-dark px-3"
              href="https://github.com/mdbootstrap/mdb-ui-kit"
              role="button"
              ><i class="fab fa-github"></i
            ></a>
          </div>
        </div>
        <!-- Collapsible wrapper -->
      </div>
      <!-- Container wrapper -->
    </nav>
    <!-- Navbar -->


    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
    ></script>
  </body>
</html>

app/views/tweets/_form.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
        rel="stylesheet"
      />
      <!-- Google Fonts -->
      <link
        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        rel="stylesheet"
      />
      <!-- MDB -->
      <link
        href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
        rel="stylesheet"
      />
    <title>New Tweet</title>
  </head>
  <body>

    <div class="container mt-44">

      <div class="row">

        <div class="text-center" style="padding-left: 300px; padding-right: 300px;">
          <br>
          <h2 class="text-center">New Tweet</h2>

          <div class="card mt-8">

            <div class="card-body" >
              <%= form_with(model: @tweet, local: true, url: confirm_path) do |form| %>
                <% if tweet.errors.any? %>
                  <div id="error_explanation">
                    <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

                    <ul>
                      <% tweet.errors.each do |error| %>
                        <li><%= error.full_message %></li>
                      <% end %>
                    </ul>
                  </div>
                <% end %>

                <div class="">
                  <%= form.label :Title,  class: "form-label" %>
                  <%= form.text_field :Title, class: "form-control", :required => 'required' %>
                </div>
                <br>
                <div class="field">
                  <%= form.label :Content,  class: "form-label" %>
                  <%= form.text_area :Content, class: "form-control", :rows => 04, :required => 'required', :maxlength => 140 %>
                </div>

                <div class="actions">
                  <%= form.submit %>
                  <%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %>
                </div>
              <% end %>
            </div>
          </div>
          <div class="col-md-4">

          </div>
        </div>

      </div>


    </div>


  </body>
</html>

app/views/tweets/confirm.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
        rel="stylesheet"
      />
      <!-- Google Fonts -->
      <link
        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        rel="stylesheet"
      />
      <!-- MDB -->
      <link
        href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
        rel="stylesheet"
      />
    <title>Confirmation</title>
  </head>
  <body>



    <div class="container mt-44">

        <h2 class="text-center mb-8">Confim your tweet</h2>
      <div class="row mt-48 text-center">
        <div class="col-md-4">

        </div>
        <div class="col-md-4">
          <h2>Title:</h2> <%= @tweet.Title %><hr>
          <h2>Content:</h2> <%= @tweet.Content %>
        </div>
        <div class="col-md-4">

        </div>




        <%= form_with(model: @tweet, local: true) do |form| %>
        <%= form.hidden_field :Title %>
        <%= form.hidden_field :Content %>
        <%= form.submit %>
        <% end %>
      </div>

    </div>



    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
    ></script>
  </body>
</html>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link
        href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
        rel="stylesheet"
      />
      <!-- Google Fonts -->
      <link
        href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        rel="stylesheet"
      />
      <!-- MDB -->
      <link
        href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.css"
        rel="stylesheet"
      />
    <title>Accueil</title>
  </head>
  <body>



    <div class="container mt-44">
        <h2 class="text-center mb-8">Les dernières tweets</h2>
      <div class="row mt-48">

        <div class="col-md-1">

        </div>

        <div class="col-md-10">

          <div class="row mb-5">
            <% @tweets.each do |tweet| %>
              <div class="col-md-4 mb-5">

                <div class="card text-center mt-8">

                  <div class="card-header">Title of tweet :<%= tweet.Title %></div>

                  <div class="card-body">
                    <p class="card-text">Content : <%= tweet.Content %></p>
                    <p class="card-text">Written by : <%= tweet.user.email %></p>

                  </div>

                  <div class="card-footer text-muted">
                    <%= link_to 'Show', tweet %> |
                    <%= link_to 'Edit', edit_tweet_path(tweet) %> |
                    <%= link_to 'Destroy', destroy_path(tweet['id']), :method => :delete, :confirm => "Are you sure?" %>

                  </div>

                </div>

              </div>
         <% end %>



          </div>


        </div>

        <div class="col-md-1">

        </div>


      </div>

    </div>
    <div class="container text-center ">
      <button type="button" name="button" class="btn btn-info"><a href="/tweets/new">New Tweet</a></button>
    </div>

    <div class="container text-center mb-5">

    </div>

    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/3.6.0/mdb.min.js"
    ></script>
  </body>
</html>

app/views/tweets/new.html.erb
<div class="" style="text-align: center;">
  <h1>Bienvenue sur Tweet</h1>

  <%= render 'form', tweet: @tweet %>
  <br>
  <%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tweet.Title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @tweet.Content %>
</p>

<p>
  <strong>User:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>